# Create a GitHub action to email a report from a file at 6 a.m. daily

name: Deploy App

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
    - name: Email report
      env:
        SMTP_SERVER: smtp.example.com
        SMTP_PORT: 587
        SMTP_USER: